### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by stelgenhof** [hamburgscleanest/laravel-guzzle-throttle#6] opened 2018-11-09 01:57 UTC
Hi,

First of all thanks for this great package! Works perfectly :)
Not so much of an issue, but a few remarks regarding the documentation:

- The examples use the GuzzleThrottle class, however since this is the Laravel wrapper it maybe better to show/use the LaravelGuzzleThrottle class in the examples.
- When you have published the configuration, it maybe necessary to do a `php artisan config:clear` if the config is cached. Without this, you will encounter errors from this package. I got a 'Please provide a cache driver' error, even though it was set correctly. Maybe a good idea to mention this in the documentation :)

Cheers! Sacha

**Comment by Chroma91** [comment] 2018-11-11 15:54
I updated the reference to the class in the documentation. I will close this issue for now. The config should actually be cleared by default as you found out. I was not able to reproduce it.

**Closed by Chroma91** 2018-11-11 15:54 UTC
